### ISSUE TITLE
docking

### ISSUE THREAD

**Issue by bbyjr** [MolAICal/molaical.github.io#6]
Dear Dr.
I want to use the docking to filter, please ask if MolAICal provides bulk docking.
And then,I want to know generate with tutorial 0 and then docking, compared with use the tutorial 3 directly, is it the same?

**Comment by MolAICal** [comment]
Yes, tutorial 3 is drug virtual screening that is equal to bulk docking.
In addition, tutorial 3 is different with tutorial 0 due to algorithm differences. 
In tutorial 0, it uses genetic algorithm (GA) and deep learning model to generate new molecules in receptor pocket. 
In tutorial 3, docking does not employ GA, it uses monte Carlo algorithm, etc.

But, you can combine or compare generation and docking method for your project or research.

Best,
Qifeng Bai

**Comment by MolAICal** [comment]
> Dear Dr. I want to use the docking to filter, please ask if MolAICal provides bulk docking. And then,I want to know generate with tutorial 0 and then docking, compared with use the tutorial 3 directly, is it the same?

Yes, tutorial 3 is drug virtual screening that is equal to bulk docking.
In addition, tutorial 3 is different with tutorial 0 due to algorithm differences.
In tutorial 0, it uses genetic algorithm (GA) and deep learning model to generate new molecules in receptor pocket.
In tutorial 3, docking does not employ GA, it uses monte Carlo algorithm, etc.

But, you can combine or compare generation and docking method for your project or research.

Best,
Qifeng Bai
